name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@1.88
        with:
          components: clippy,rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test --all-targets
      - name: Test Wake-on-LAN support library
        run: >-
          cargo test
          --manifest-path examples/wake-on-lan/Cargo.toml
          --target x86_64-unknown-linux-gnu
